### ISSUE TITLE
S1A - Decide whether to revise lighter click

### ISSUE THREAD

**Issue by whymog** [whymog/efjm#11]
Based on [this thread](https://github.com/whymog/efjm/pull/8#discussion_r209491870), there's been some discussion about how to handle the moment where the lighter is clicked. In order to get S1A merged into master, I've tabled that thread and moved it into this issue for discussion!

**Comment by catdad666** [comment]
I like the sound effect as the link to the next passage. I think it reads naturally, but I see @thenthdegree's point.

How does everyone feel about flipping the paragraphs and keeping the sound effect as the link? Does having the click noise before the description of flicking the lighter read better?

**Comment by whymog** [comment]
Hmm. Not to me, honestly. Especially now that the image is in. It reads better to me if the link is the final thing you see on the page before you're taken to the new hub page that includes the lit-up image.

**Comment by thenthdegree** [comment]
Thinking it over last night, I had four different ideas, in increasing degrees of changes/work:

1. Change `* click *` to something like `* flckk *` to echo & tie closer into the "flick" action in the current description. (Since clicking is also the literal interaction model for the game, it could also come across as a simple command to the player to click, which is an aesthetic I don't dig.)

2. Rephrase the line to put action/transition link at the end:
> The room sprang into detail around me as I gave the lighter a `* flckk *`

3. Introduce a new passage w/ an animation between dark & lit illos to savor the "solution complete!" moment? I could see this being something like:
>I gave it a good **flick**, and the room sprang into detail around me.

Then **flick** (or something) is a link to the new passage, which has `* click *` or etc. at the top and the dark port-a-potty illo below that; interacting with `* click *` switches the illo to the lit image. Then the hub passage after that has the lit room illo, text & rest of the scene. Maybe it could transition from that middle passage automatically a set time after clicking & switching images. Or something else?

4. Lean into the possible disorientation of the interaction (description of action -> player recapitulation), adding more interactions in that style, making it a running element of the darkened portion of the port-a-potty sequence. Then the stylistic shift (as compared to the bulk of interactions in the rest of the text) would thematically reflect the before/after change of finally understanding your surroundings & situation.

**Comment by catdad666** [comment]
Option 2 works for me as the easiest fix. Would be interested to see how option 3 would look in practice, because I think pausing even more on the transition between dark and light could be pretty neat. But, it's more a nice thing to have and not a requirement at this point.

**Comment by thenthdegree** [comment]
I'm of a similar mind. #3 seems cool, but something that could be done later if desired. #4 would be a big change, and only something I'd actually push for if we decided we wanted/needed it.

**Comment by whymog** [comment]
Ooh, I like option #3 the best, and that's a good point in option #1 re: "click" also being a generic input verb. Some minor CSS trickery behind a one-shot passage would be all we need:

```
(set: $portapottyLit to false)
I gave it a good **[[flick|Jail Cell (Unlit) - light up room]]**...
// ... which takes us to that passage ...
// ... where we show unlit image, 
// ... CSS opacity transition to lit image overlaid, 
// ...and show one-shot text of "I gave it a good flick...and the room sprang into detail around me." and provide a link to Jail Cell (Unlit) - hub
```

I vote we go for this. I'm happy to take a stab at it.

**Comment by thenthdegree** [comment]
Dope!

**Comment by whymog** [comment]
Still need to figure out the CSS overlay transition, but it's next on my list!

**Comment by whymog** [comment]
Deprioritized for v1 because Harlowe hates HTML soooooo much
